import type { AdminMetric, Category, Product, StorySeries } from "@/lib/types";
import { luxuryPricingBasis, suggestStartPrice } from "@/lib/pricing";

type DailyProductSeed = {
  serial: string;
  title: string;
  seriesId: string;
  category: Category;
  zhTitle: string;
  image: string;
  materialLine: string;
  craftLine: string;
  storyLine: string;
};

export const brand = {
  name: "NOIRVEN",
  cnName: "诺梵",
  proposition: "每一次归属，都是一次拯救。",
  secondary: "举世无双，只由唯一确认。",
  story:
    "Noirven 诺梵相信，真正独一无二的顶级奢侈品级作品，不该被流行审判。每一件作品都只有一个实体、一个编号和一段不可复制的故事；不复制，不复刻，不再生产。一旦付款被确认，它从此只归一人；若尚未归属，它不会被放弃，而是继续等待下一次被看见。",
  cta: "查看顶奢作品",
  storyCta: "品牌故事",
};

export const materialLibrary = {
  metals: ["玫瑰金", "雕金", "黄金", "铂金", "钯金", "钛金属", "黑铑铂金", "陨铁", "黑陶瓷", "锆陶瓷"],
  stones: [
    "天然白钻",
    "彩色宝石",
    "青金石",
    "贝母",
    "孔雀石",
    "蓝宝石",
    "祖母绿",
    "红宝石",
    "帕拉伊巴碧玺",
    "沙弗莱石",
    "尖晶石",
    "坦桑石",
    "欧泊",
    "月光石",
    "黑贝母",
    "海蓝宝",
    "烟晶",
    "白水晶",
    "玉髓",
    "珍珠母贝",
  ],
  craft: [
    "珐琅彩",
    "钢琴烤漆",
    "鎏金",
    "鎏彩",
    "景泰蓝",
    "玑镂雕纹",
    "微密镶",
    "隐秘式镶嵌",
    "雪花镶",
    "手工錾刻",
    "错金银",
    "冷珐琅",
    "半透明珐琅",
    "贝母薄片镶嵌",
    "钛金属阳极氧化",
    "陶瓷烧结",
    "镜面抛光",
    "拉丝雾面",
  ],
};

export const materialNarratives = [
  {
    title: "Night Metal",
    zhTitle: "夜色金属",
    story: "黑铑铂金、钛金属与陨铁承载低声、克制和反转，不负责闪耀，只负责留下无法复制的轮廓。",
    materials: ["黑铑铂金", "钛金属", "陨铁"],
    craft: ["拉丝雾面", "镜面抛光", "钛金属阳极氧化"],
  },
  {
    title: "Living Blue",
    zhTitle: "会呼吸的蓝",
    story: "青金石、海蓝宝与帕拉伊巴碧玺用于等待、归潮和远行，让蓝色不只是颜色，而是一种被重新认出的方向。",
    materials: ["青金石", "海蓝宝", "帕拉伊巴碧玺"],
    craft: ["隐秘式镶嵌", "半透明珐琅", "水纹雕刻"],
  },
  {
    title: "Archive Light",
    zhTitle: "档案之光",
    story: "贝母、黑贝母、月光石和欧泊像被保存的记忆，适合月相、告别、秘密与迟来的理解。",
    materials: ["贝母", "黑贝母", "月光石", "欧泊"],
    craft: ["贝母薄片镶嵌", "玑镂雕纹", "微刻封存线"],
  },
  {
    title: "Verdict Green",
    zhTitle: "裁决之绿",
    story: "孔雀石、沙弗莱石与祖母绿为 Justice of One 建立证据感，像一道安静但不可反驳的判定。",
    materials: ["孔雀石", "沙弗莱石", "祖母绿"],
    craft: ["景泰蓝", "手工錾刻", "错金银"],
  },
  {
    title: "Burned Bloom",
    zhTitle: "灰烬盛开",
    story: "黑陶瓷、烟晶、暗红珐琅和红宝石表达重建之后的生命感，让花不是柔弱符号，而是废墟里的证词。",
    materials: ["黑陶瓷", "烟晶", "红宝石"],
    craft: ["陶瓷烧结", "冷珐琅", "局部鎏彩"],
  },
  {
    title: "Soft Armor",
    zhTitle: "柔性盔甲",
    story: "钯金、碳纤维、粉玉髓和白玛瑙服务于温柔盔甲：柔软不是退让，而是带边界的保护。",
    materials: ["钯金", "碳纤维", "粉玉髓", "白玛瑙"],
    craft: ["碳纤维层压", "微密镶", "钢琴烤漆"],
  },
];

export const storySeries: StorySeries[] = [
  {
    id: "still-here",
    name: "Still Here",
    zhName: "仍在这里",
    theme: "低谷之后仍然站在这里。",
    emotionalLine: "我还在，所以光也还在。",
    description:
      "为从低谷中重新认领自己的人而生。作品常带有不完全闭合的曲线、克制的裂隙和一个微小光点，像证明：伤口之后，仍有形态。",
    categories: ["ring", "bracelet", "brooch"],
    materials: ["铂金", "玫瑰金", "黑铑铂金", "天然白钻", "烟晶"],
    craft: ["珐琅彩", "钢琴烤漆", "半透明珐琅", "微密镶"],
    visualMemory: ["不完全闭合曲线", "小面积光点", "隐藏编号", "克制裂隙"],
    ipHook: "一位匿名买家 Still Here 拍下 N-0007 后，Noirven 确定了尚未归属的作品继续等待的规则。",
  },
  {
    id: "unclaimed-star",
    name: "Awaiting Star",
    zhName: "待归之星",
    theme: "有些光不属于人群，只等待唯一能读懂它的人。",
    emotionalLine: "不是无人喜欢，只是尚未遇见唯一的主人。",
    description:
      "为长期等待、最终与唯一主人互相确认的存在而生。作品避免直接星形，而用单颗宝石、悬浮细线和大面积留白表达命定归属之前的安静光芒。",
    categories: ["necklace", "stud", "earring"],
    materials: ["铂金", "青金石", "珍珠母贝", "帕拉伊巴碧玺", "天然白钻"],
    craft: ["珐琅彩", "鎏彩", "隐秘式镶嵌", "贝母薄片镶嵌"],
    visualMemory: ["单颗宝石", "悬浮细线", "大面积留白", "非具象星点"],
    ipHook: "每一轮尚未归属都会成为作品档案的一部分：它不是被遗忘，而是在等一个能与它互相确认的人。",
  },
  {
    id: "seventh-light",
    name: "Seventh Light",
    zhName: "第七日的光",
    theme: "七日之后，光没有消失，而是归于某个人。",
    emotionalLine: "第七日，光有了归属。",
    description:
      "围绕“被看见的那一刻”而生的核心系列。七段细线、偏移亮点和时间刻度构成隐性记忆，表达归属发生在命运转身处。",
    categories: ["ring", "earring", "watch"],
    materials: ["黄金", "玫瑰金", "彩色宝石", "尖晶石", "天然白钻"],
    craft: ["鎏金", "鎏彩", "景泰蓝", "雪花镶"],
    visualMemory: ["七段细线", "时间刻度", "偏移亮点", "不对称结构"],
    ipHook: "每一件 Seventh Light 都有一段最后一小时的命运反转。",
  },
  {
    id: "justice-of-one",
    name: "Justice of One",
    zhName: "唯一的证明",
    theme: "让被低估的独特，获得一次公平展示。",
    emotionalLine: "不由多数定义，只由唯一确认。",
    description:
      "为被低估、被误读、但仍然锋利完整的存在而生。作品强调平衡线、偏心宝石和一处像证据一样的光。",
    categories: ["brooch", "bracelet", "ring"],
    materials: ["雕金", "孔雀石", "沙弗莱石", "祖母绿", "天然白钻"],
    craft: ["景泰蓝", "鎏金", "手工錾刻", "错金银"],
    visualMemory: ["平衡线", "偏心结构", "锋利转折", "单颗宝石证据"],
    ipHook: "作品像一份无声证词，不需要多数投票来证明自己的价值。",
  },
  {
    id: "ash-garden",
    name: "Ash Garden",
    zhName: "灰烬花园",
    theme: "从被烧毁的地方，重新长出不需要许可的花。",
    emotionalLine: "灰烬不是结束，是另一种盛开。",
    description:
      "为经历过崩塌、失去、沉默重建的人而生。作品不以明亮金属为主，而用黑陶瓷、烟晶、黑曜石、暗红珐琅和钛金属形成冷静的生命感；花不是柔弱符号，而是从裂面里长出的证据。",
    categories: ["ring", "brooch", "earring"],
    materials: ["黑陶瓷", "钛金属", "烟晶", "黑曜石", "暗红珐琅", "陨铁"],
    craft: ["微雕", "冷珐琅", "陶瓷烧结", "局部鎏彩", "黑铑封层"],
    visualMemory: ["焦黑裂面", "细小花芽", "暗红光点", "非对称重生线"],
    ipHook: "Ash Garden 可以延展成废墟、幸存者、秘密花园与重建城市的长线叙事，每一件作品都是灾后第一朵花。",
  },
  {
    id: "tide-return",
    name: "Tide Return",
    zhName: "归潮",
    theme: "被海带走的东西，会以另一种光回来。",
    emotionalLine: "失去不是沉没，是等待下一次涨潮。",
    description:
      "为离开、迁徙、远行后重新回到自我的人而生。作品以贝母、海蓝宝、青金石、珍珠母贝与透明树脂水纹为记忆，弱化金属存在，让材质像潮汐一样包裹身体。",
    categories: ["necklace", "bracelet", "stud"],
    materials: ["贝母", "海蓝宝", "青金石", "欧泊", "珍珠母贝", "雾面钛"],
    craft: ["贝母薄片镶嵌", "透明珐琅", "水纹雕刻", "冷色鎏彩", "隐秘式镶嵌"],
    visualMemory: ["潮汐弧线", "半透明水纹", "漂流编号", "内侧回声线"],
    ipHook: "Tide Return 可以延展为漂流瓶、失物招领、海边旧信和归来的旅人，适合后续小说与短剧支线。",
  },
  {
    id: "tender-armor",
    name: "Tender Armor",
    zhName: "温柔盔甲",
    theme: "温柔不是退让，是选择不被击碎。",
    emotionalLine: "我柔软，但不会再被轻易打碎。",
    description:
      "为外表温和、内里坚定的人而生。作品使用碳纤维、雾面钛、粉玉髓、白玛瑙与钢琴烤漆，形成轻而坚固的护甲语言；结构可贴合身体，却保留清晰边界。",
    categories: ["bracelet", "ring", "watch"],
    materials: ["碳纤维", "雾面钛", "钯金", "粉玉髓", "白玛瑙", "钢琴烤漆"],
    craft: ["碳纤维层压", "钛金属拉丝", "钢琴烤漆", "玉髓包镶", "微密镶"],
    visualMemory: ["柔弧护甲", "隐藏铰链", "粉白内光", "边界切线"],
    ipHook: "Tender Armor 可以发展为女性守护、边界感、自我修复与城市战衣的 IP 线，适合未来游戏装备系统。",
  },
  {
    id: "moon-archive",
    name: "Moon Archive",
    zhName: "月相档案",
    theme: "月亮记得你没有说出口的每一次告别。",
    emotionalLine: "不是忘记了，只是被月光保存。",
    description:
      "为不愿公开伤口、却仍然保存记忆的人而生。作品以月光石、黑贝母、青金石、白水晶和浅色珐琅构成档案页般的层次，强调半透明、留白与编号封存。",
    categories: ["necklace", "stud", "brooch", "earring"],
    materials: ["月光石", "黑贝母", "青金石", "白水晶", "坦桑石", "浅色珐琅"],
    craft: ["半透明珐琅", "贝母薄片镶嵌", "玑镂雕纹", "水晶切面", "微刻封存线"],
    visualMemory: ["月相切片", "档案封条", "半透明留白", "低声编号"],
    ipHook: "Moon Archive 可以沉淀为秘密档案馆、月相日记、失物记忆和角色过往支线，为后续小说和短剧提供情感线索。",
  },
];

export const storyChapters = [
  {
    code: "CH-22",
    seriesId: "moon-archive",
    title: "月相档案的蓝色证词手环",
    summary:
      "N-0532 把一段终于可以被保存下来的证词做成开口手环：拉丝铂金形成克制的外轨，玫瑰金内轨像被重新点亮的档案线，月光石沿弧面渐次排开，天然白钻只在停顿处发光；偏心青金石不站在正中，而像一枚终于被归档的蓝色证词。买家说：我不再需要把所有记忆讲给别人听，我只需要它们被安静、真实地保存。",
    emotion: "档案 / 蓝色证词 / 安静保存",
    productSerial: "N-0532",
  },
  {
    code: "CH-21",
    seriesId: "justice-of-one",
    title: "唯一证明的证据线",
    summary:
      "N-0531 把一条安静但不可反驳的证据线做成可佩戴的胸针：铂金承担干净的外轮廓，雕金在内侧压出细密骨架，祖母绿不站在正中，而是偏在一侧像重新出现的证词；沙弗莱石沿着平衡线渐次收光，天然白钻只在转折处形成低声标记。买家说：我不需要被所有人看见，我只需要那条真正属于我的证据线不要再被抹去。",
    emotion: "证据 / 平衡 / 不被抹去",
    productSerial: "N-0531",
  },
  {
    code: "CH-20",
    seriesId: "tender-armor",
    title: "温柔盾甲的静锚时间",
    summary:
      "N-0530 把温柔不再漂流的时刻做成一枚安静的腕表：钛金属与钯金像软甲一样围住手腕，碳纤维格架把轻盈变成支撑，白玛瑙表盘保留一片不被打扰的空白，粉玉髓表冠像贴近脉搏的小锚，天然白钻只沿一侧低声发光。买家说：我终于不用把温柔解释成没有重量，它可以替我在时间里停稳。",
    emotion: "静锚 / 温柔 / 边界重量",
    productSerial: "N-0530",
  },
  {
    code: "CH-19",
    seriesId: "moon-archive",
    title: "月相档案的静名透镜",
    summary:
      "N-0529 把一个终于不再替别人沉默的名字，放进一枚可佩戴的月光透镜：铂金做成很薄的档案边框，黑贝母在戒面下方像夜色封页，月光石与白水晶叠成半透明的证词，淡色珐琅把编号留在内侧，白钻只沿着月弧亮成一圈低声标记。买家说：我不再替那段沉默保管名字，我把它交给月光，让它站在可以作证的位置。",
    emotion: "静名 / 作证 / 月光归档",
    productSerial: "N-0529",
  },
  {
    code: "CH-18",
    seriesId: "tide-return",
    title: "归潮的蓝账骨架",
    summary:
      "N-0528 把一次被海带走后的归来做成一圈蓝色账页：雾面钛撑起像船骨的内架，铂金把潮线收成可佩戴的弧度，海蓝宝与白水晶在外侧叠出透明水纹，帕拉伊巴碧玺只在转折处亮成坐标，珍珠母贝像重新登记过的页边。买家说：我不是回到原来的岸边，我只是把漂走的那部分自己重新认领。",
    emotion: "归来 / 认领 / 蓝色账页",
    productSerial: "N-0528",
  },
  {
    code: "CH-17",
    seriesId: "ash-garden",
    title: "灰烬花园的余温证词",
    summary:
      "N-0527 把废墟之后没有散尽的余温做成一圈靠近颈侧的证词：黑陶瓷收住外缘，玫瑰金在内侧搭出安静的骨架，陨铁纹理像无法伪造的时间，暗红珐琅与烟晶把火光压低，红宝石和白钻只在转折处亮一下。买家说：我不需要回到没有燃烧以前，我只需要证明，灰烬之后仍有我自己的温度。",
    emotion: "余温 / 证词 / 重建",
    productSerial: "N-0527",
  },
  {
    code: "CH-16",
    seriesId: "seventh-light",
    title: "第七日的七衡光晕",
    summary:
      "N-0526 把第七日最后一小时做成一枚偏心光晕：黑贝母盘面没有追求完整圆形，七道金线从玫瑰金轴心向外校准，蓝宝石像迟到后终于被看见的坐标，坦桑石与白钻沿着不对称外缘留下一圈低声光。买家说：我不再把迟到解释成错过，我只确认那束光终于按我的时间抵达。",
    emotion: "归属 / 最后一小时 / 校准",
    productSerial: "N-0526",
  },
  {
    code: "CH-15",
    seriesId: "still-here",
    title: "仍在这里的静阀回声",
    summary:
      "N-0525 把裂缝做成一枚可以呼吸的静阀：黑铑铂金没有遮住断口，钯金内线把它重新拉成秩序，烟晶像低声保留的证词，唯一一颗白钻只在偏心处亮一下。买家说：我不需要别人把我救回原样，我只需要确认，裂缝之后的我仍然可以选择光从哪里经过。",
    emotion: "救回 / 裂缝 / 自我秩序",
    productSerial: "N-0525",
  },
  {
    code: "CH-14",
    seriesId: "justice-of-one",
    title: "唯一证明的绿密裁决",
    summary:
      "N-0524 把被误读的绿色压成一枚很安静的密钥：祖母绿不站在中央讨好任何人，孔雀石的纹理像被重新排列的证词，沙弗莱与白钻只在不对称的边线发光。买家说：我不需要赢过所有人，我只需要把那份被误判的自己交还给自己。",
    emotion: "反转 / 证明 / 归还自己",
    productSerial: "N-0524",
  },
  {
    code: "CH-13",
    seriesId: "unclaimed-star",
    title: "待归之星的子午低语",
    summary:
      "N-0523 没有把等待做成一颗直白的星，而是把它拉成一条很安静的子午线：珍珠母贝像未寄出的信，水晶透镜把迟来的光折回自己，帕拉伊巴与坦桑石只在边缘亮一下。买家说：我不是在原地等谁，我是在沿着自己的轨道抵达自己。",
    emotion: "等待 / 抵达 / 唯一识别",
    productSerial: "N-0523",
  },
  {
    code: "CH-12",
    seriesId: "moon-archive",
    title: "月相档案的封存索引",
    summary:
      "N-0522 把一个不再愿意替人保密的名字，封存进黑贝母与水晶透镜之间：不是为了报复，而是为了让真相有归档的位置。买家说：我终于不用再替任何人扛住沉默，月光会替我作证。",
    emotion: "证据 / 告别 / 自己",
    productSerial: "N-0522",
  },
  {
    code: "CH-11",
    seriesId: "tender-armor",
    title: "温柔盾甲的格架应答",
    summary:
      "N-0521 用碳纤维与钛金属切线写下一个很冷静的答案：边界不是墙，是你在温柔里仍然完整的骨架。它不让你再用退让来和解，也不需要用冷硬来护你。那天，买家把它戴在视线看不见的内腕，说：我终于不用再解释我的温柔，它有自己的等式。",
    emotion: "边界 / 温柔 / 修复",
    productSerial: "N-0521",
  },
  {
    code: "CH-10",
    seriesId: "tide-return",
    title: "归潮的回执：我自己的反证",
    summary:
      "N-0520 并没有用光炫耀一次回来，它用一个很小的细节讨论你是否真的回来：请用手触到手感，感到蓝色不是对错，是方向。买家把它签收在背光的时刻，说：我只想让自己那一部分终于有收到一个回执而已。",
    emotion: "回来 / 收到 / 调整",
    productSerial: "N-0520",
  },
  {
    code: "CH-01",
    seriesId: "ash-garden",
    title: "灰烬花园的第一封信",
    summary:
      "一位买家没有留下真名，只写下：我不是想回到从前，我只是想证明废墟也能开花。于是 Ash Garden 成为 Noirven 第一条非明亮金属主导的故事线。",
    emotion: "重建、幸存、反转",
    productSerial: "N-0512",
  },
  {
    code: "CH-02",
    seriesId: "tide-return",
    title: "归潮的蓝色收据",
    summary:
      "N-0520 曾经连续等待数轮，直到一位远行多年的人在涨潮日拍下它。她说：我不是回来找谁，我是回来确认自己。",
    emotion: "离开、回归、救赎",
    productSerial: "N-0509",
  },
  {
    code: "CH-03",
    seriesId: "tender-armor",
    title: "温柔盔甲的边界",
    summary:
      "它看起来轻，实际很难被折断。买家把它戴在手腕内侧，像把一句没有说出口的“不”刻进身体。",
    emotion: "边界、保护、清醒",
    productSerial: "N-0503",
  },
  {
    code: "CH-04",
    seriesId: "moon-archive",
    title: "月相档案馆",
    summary:
      "每一件 Moon Archive 都像一页被月光封存的档案。它不替人遗忘，只负责把无法说出口的部分保存到被理解那天。",
    emotion: "记忆、告别、保存",
    productSerial: "N-0504",
  },
  {
    code: "CH-05",
    seriesId: "unclaimed-star",
    title: "待归之星的静默轨道",
    summary:
      "它没有寻找所有人的目光，只在自己的轨道上发亮。直到某个夜晚，一个人停下来，说：这不是等待我购买，它像是在等待我承认自己。",
    emotion: "等待、命定、唯一确认",
    productSerial: "N-0505",
  },
  {
    code: "CH-06",
    seriesId: "justice-of-one",
    title: "裁决之绿的证词",
    summary:
      "孔雀石的纹路像一份没有签名的证词，沙弗莱石在偏心处发光。它提醒佩戴者：真正的价值不需要多数人举手。",
    emotion: "正义、证明、反转",
    productSerial: "N-0506",
  },
  {
    code: "CH-07",
    seriesId: "still-here",
    title: "黑铑裂隙里的白钻",
    summary:
      "一枚白钻被放在最克制的裂隙旁，不像装饰，更像一句仍然活着的回答。Still Here 从不掩饰裂痕，它把裂痕变成光经过的地方。",
    emotion: "存活、修复、微光",
    productSerial: "N-0507",
  },
  {
    code: "CH-08",
    seriesId: "seventh-light",
    title: "最后一小时的红色指针",
    summary:
      "第七日最后一小时，红宝石像被推迟的心跳。它不催促任何人，只把归属发生前的紧张与温柔固定在金线之间。",
    emotion: "时刻、归属、命运",
    productSerial: "N-0508",
  },
  {
    code: "CH-09",
    seriesId: "ash-garden",
    title: "灰烬花园的陨铁证词",
    summary:
      "N-0519 的陨铁切片不是装饰，更像一份由天外落进废墟的证据。它记得灰烬的呼吸，也记得被抛下后的沉默。买家把它别在内衬里，说：我不需要任何人的同情宣告，我只需要一个可以善待自己的证明。",
    emotion: "重建、证据、反转",
    productSerial: "N-0519",
  },
];

export const dailyProductSeeds: DailyProductSeed[] = [
  {
    serial: "N-0532",
    title: "Moon Archive Blue Witness Cuff Bracelet",
    seriesId: "moon-archive",
    category: "bracelet",
    zhTitle: "月相档案蓝色证词手环",
    image: "/assets/products/n-0532-moon-archive-blue-witness-cuff-bracelet.png",
    materialLine: "铂金 / 玫瑰金 / 月光石 / 青金石 / 淡色珐琅 / 天然白钻",
    craftLine: "拉丝抛光 / 爪镶 / 珐琅嵌线 / 微密镶 / 开口手环成形",
    storyLine: "有些记忆不必再反复解释，只需要被安静、真实地保存下来。",
  },
  {
    serial: "N-0531",
    title: "Justice of One Evidence Line Brooch",
    seriesId: "justice-of-one",
    category: "brooch",
    zhTitle: "唯一证明证据线胸针",
    image: "/assets/products/n-0531-justice-of-one-evidence-line-brooch.png",
    materialLine: "铂金 / 雕金 / 祖母绿 / 沙弗莱石 / 天然白钻",
    craftLine: "手工錾刻 / 隐秘式镶嵌 / 微密镶 / 镜面抛光",
    storyLine: "真正属于自己的证据线，不需要喧哗，也不该再被抹去。",
  },
  {
    serial: "N-0530",
    title: "Tender Armor Quiet Anchor Watch",
    seriesId: "tender-armor",
    category: "watch",
    zhTitle: "温柔盾甲静锚腕表",
    image: "/assets/products/n-0530-tender-armor-quiet-anchor-watch.png",
    materialLine: "钛金属 / 钯金 / 碳纤维 / 白玛瑙 / 粉玉髓 / 黑色钢琴烤漆 / 天然白钻",
    craftLine: "钛金属拉丝 / 碳纤维层压 / 玉髓包镶 / 微密镶 / 镜面抛光",
    storyLine: "温柔不是没有重量，而是在时间里替自己落下一枚安静的锚。",
  },
  {
    serial: "N-0529",
    title: "Moon Archive Quiet Name Lens Ring",
    seriesId: "moon-archive",
    category: "ring",
    zhTitle: "月相档案静名透镜戒",
    image: "/assets/products/n-0529-moon-archive-quiet-name-lens-ring.png",
    materialLine: "铂金 / 黑贝母 / 月光石 / 白水晶 / 淡色珐琅 / 天然白钻",
    craftLine: "贝母薄片镶嵌 / 水晶切面 / 微刻封存线 / 隐秘式镶嵌 / 镜面抛光",
    storyLine: "有些名字不需要再替别人沉默，只需要被月光安放在可以作证的位置。",
  },
  {
    serial: "N-0528",
    title: "Tide Return Blue Ledger Cuff Bracelet",
    seriesId: "tide-return",
    category: "bracelet",
    zhTitle: "归潮蓝账骨架手环",
    image: "/assets/products/n-0528-tide-return-blue-ledger-cuff-bracelet.webp",
    materialLine: "铂金 / 雾面钛 / 海蓝宝 / 帕拉伊巴碧玺 / 白水晶 / 珍珠母贝 / 天然白钻",
    craftLine: "水纹雕刻 / 隐秘式镶嵌 / 玑镂雕纹 / 微密镶 / 镜面抛光",
    storyLine: "真正的回潮不是原路返回，而是把漂走的自己重新登记在蓝色里。",
  },
  {
    serial: "N-0527",
    title: "Ash Garden Ember Witness Collar Necklace",
    seriesId: "ash-garden",
    category: "necklace",
    zhTitle: "灰烬花园余温证词项圈",
    image: "/assets/products/n-0527-ash-garden-ember-witness-collar-necklace.webp",
    materialLine: "黑陶瓷 / 玫瑰金 / 陨铁 / 暗红珐琅 / 烟晶 / 红宝石 / 天然白钻",
    craftLine: "陶瓷烧结 / 手工錾刻 / 半透明珐琅 / 雪花镶 / 镜面抛光",
    storyLine: "灰烬之后的余温不是残留，而是自己仍然存在的证词。",
  },
  {
    serial: "N-0526",
    title: "Seventh Light Sevenfold Halo Watch",
    seriesId: "seventh-light",
    category: "watch",
    zhTitle: "第七日七衡光晕腕表",
    image: "/assets/products/n-0526-seventh-light-sevenfold-halo-watch.jpg",
    materialLine: "玫瑰金 / 黄金 / 贝母盘面 / 蓝宝石 / 坦桑石 / 天然白钻",
    craftLine: "微刻时标 / 玑镂雕纹 / 雪花镶 / 镜面抛光 / 鎏彩",
    storyLine: "第七道光不再追问迟到，它在最后一小时把归属校准成自己的时间。",
  },
  {
    serial: "N-0525",
    title: "Still Here Quiet Valve Brooch",
    seriesId: "still-here",
    category: "brooch",
    zhTitle: "仍在这里静阀回声胸针",
    image: "/assets/products/n-0525-still-here-quiet-valve-brooch.png",
    materialLine: "黑铑铂金 / 钯金 / 烟晶 / 灰色尖晶石 / 天然白钻",
    craftLine: "镜面抛光 / 拉丝雾面 / 微密镶 / 手工錾刻 / 钢琴烤漆",
    storyLine: "裂缝不是等待别人修复的证据，而是自己重新规定光路的静阀。",
  },
  {
    serial: "N-0524",
    title: "Justice of One Verdant Cipher Ring",
    seriesId: "justice-of-one",
    category: "ring",
    zhTitle: "唯一证明绿密裁决戒",
    image: "/assets/products/n-0524-justice-of-one-verdant-cipher-ring.png",
    materialLine: "黑铑铂金 / 雕金 / 孔雀石 / 沙弗莱石 / 祖母绿 / 天然白钻",
    craftLine: "景泰蓝 / 错金银 / 手工錾刻 / 隐秘式镶嵌 / 镜面抛光",
    storyLine: "真正的反转不是赢过人群，而是把被误读的绿色交还给自己。",
  },
  {
    serial: "N-0523",
    title: "Awaiting Star Meridian Whisper Earrings",
    seriesId: "unclaimed-star",
    category: "earring",
    zhTitle: "待归之星子午低语耳坠",
    image: "/assets/products/n-0523-awaiting-star-meridian-whisper-earrings.png",
    materialLine: "铂金 / 珍珠母贝 / 坦桑石 / 白水晶 / 天然白钻 / 帕拉伊巴碧玺",
    craftLine: "隐秘式镶嵌 / 贝母薄片镶嵌 / 水晶切面 / 雪花镶 / 镜面抛光",
    storyLine: "不是所有等待都在原地，有些光沿着自己的子午线抵达唯一的人。",
  },
  {
    serial: "N-0522",
    title: "Moon Archive Sealed Index Pendant",
    seriesId: "moon-archive",
    category: "necklace",
    zhTitle: "月相档案封存索引吊坠",
    image: "/assets/products/n-0522-moon-archive-sealed-index-pendant.png",
    materialLine: "铂金 / 黑贝母 / 水晶透镜 / 灰月光石 / 淡灰珐琅 / 天然白钻",
    craftLine: "贝母薄片镶嵌 / 半透明珐琅 / 玑镂雕纹 / 微刻封存线 / 镜面抛光",
    storyLine: "有些名字不需要被原谅，只需要被归档。",
  },
  {
    serial: "N-0521",
    title: "Tender Armor Lattice Cuff Bracelet",
    seriesId: "tender-armor",
    category: "bracelet",
    zhTitle: "温柔盾甲格架手环",
    image: "/assets/products/n-0521-tender-armor-lattice-cuff-bracelet.png",
    materialLine: "碳纤维 / 雾面钛 / 钯金 / 粉玉髓 / 白玛瑙 / 天然白钻",
    craftLine: "碳纤维层压 / 钢琴烤漆 / 微密镶 / 拉丝雾面 / 镜面抛光",
    storyLine: "边界不是墙，是你在温柔里仍然完整的骨架。",
  },
  {
    serial: "N-0520",
    title: "Tide Return Receipt Glow Earrings",
    seriesId: "tide-return",
    category: "earring",
    zhTitle: "归潮回执流光耳坠",
    image: "/assets/products/n-0520-tide-return-receipt-glow-earrings.png",
    materialLine: "铂金 / 帕拉伊巴碧玺 / 透明水晶 / 白水晶 / 天然白钻",
    craftLine: "隐秘式镶嵌 / 半透明珐琅 / 水晶切面 / 微密镶 / 镜面抛光",
    storyLine: "回来不是把旧的再走完，而是把等待收到收到。",
  },
  {
    serial: "N-0501",
    title: "Justice of One Oracle Bracelet",
    seriesId: "justice-of-one",
    category: "bracelet",
    zhTitle: "唯一的证明孔雀石谕令手链",
    image: "/assets/products/n-0501-justice-oracle-bracelet.png",
    materialLine: "雕金 / 孔雀石 / 沙弗莱石 / 天然白钻",
    craftLine: "手工錾刻 / 微密镶 / 鎏金 / 隐秘式镶嵌",
    storyLine: "真正的裁决不是喧哗，而是让被低估的绿重新被看见。",
  },
  {
    serial: "N-0502",
    title: "Tide Return Opal Dawn Pendant",
    seriesId: "tide-return",
    category: "necklace",
    zhTitle: "归潮欧泊晨曦项链",
    image: "/assets/products/n-0502-tide-return-opal-pendant.png",
    materialLine: "玫瑰金 / 欧泊 / 天然白钻 / 透明水晶",
    craftLine: "半透明珐琅 / 微密镶 / 贝母薄片镶嵌",
    storyLine: "潮水退去后留下的不是空缺，而是下一次归来的光。",
  },
  {
    serial: "N-0503",
    title: "Tender Armor Moon Cuff",
    seriesId: "tender-armor",
    category: "bracelet",
    zhTitle: "温柔盔甲月光手环",
    image: "/assets/products/n-0503-tender-armor-moon-cuff.png",
    materialLine: "黑陶瓷 / 月光石 / 铂金 / 天然白钻",
    craftLine: "陶瓷烧结 / 微密镶 / 半透明珐琅 / 镜面抛光",
    storyLine: "温柔不是退让，是把边界做成可以被佩戴的盔甲。",
  },
  {
    serial: "N-0504",
    title: "Moon Archive Black Nacre Earrings",
    seriesId: "moon-archive",
    category: "earring",
    zhTitle: "月相档案黑贝母耳环",
    image: "/assets/products/n-0504-moon-archive-black-nacre-earrings.png",
    materialLine: "黑贝母 / 坦桑石 / 月光石 / 天然白钻",
    craftLine: "贝母薄片镶嵌 / 微密镶 / 半透明珐琅 / 微刻封存线",
    storyLine: "有些告别不能公开，于是月光替它们保存成一对黑色档案。",
  },
  {
    serial: "N-0505",
    title: "Awaiting Star Paraiba Necklace",
    seriesId: "unclaimed-star",
    category: "necklace",
    zhTitle: "待归之星帕拉伊巴项链",
    image: "/assets/products/n-0505-awaiting-star-necklace.png",
    materialLine: "铂金 / 帕拉伊巴碧玺 / 珍珠母贝 / 天然白钻",
    craftLine: "隐秘式镶嵌 / 贝母薄片镶嵌 / 半透明珐琅",
    storyLine: "有些光不属于人群，只等待唯一能读懂它的人。",
  },
  {
    serial: "N-0506",
    title: "Justice of One Verdict Green Brooch",
    seriesId: "justice-of-one",
    category: "brooch",
    zhTitle: "唯一的证明裁决绿胸针",
    image: "/assets/products/n-0506-justice-verdict-brooch.png",
    materialLine: "雕金 / 孔雀石 / 沙弗莱石 / 天然白钻",
    craftLine: "手工錾刻 / 景泰蓝 / 错金银 / 微密镶",
    storyLine: "真正的价值，不需要多数人举手。",
  },
  {
    serial: "N-0507",
    title: "Still Here Obsidian Rift Ring",
    seriesId: "still-here",
    category: "ring",
    zhTitle: "仍在这里黑铑裂光戒",
    image: "/assets/products/n-0507-still-here-rift-ring.png",
    materialLine: "黑铑铂金 / 玫瑰金 / 烟晶 / 天然白钻",
    craftLine: "钢琴烤漆 / 半透明珐琅 / 微密镶",
    storyLine: "裂痕不是终点，是光经过的地方。",
  },
  {
    serial: "N-0508",
    title: "Seventh Light Ruby Watch",
    seriesId: "seventh-light",
    category: "watch",
    zhTitle: "第七日红曜腕表",
    image: "/assets/products/n-0508-seventh-light-watch.png",
    materialLine: "黄金 / 玫瑰金 / 红宝石 / 贝母盘面",
    craftLine: "玑镂雕纹 / 鎏彩 / 雪花镶 / 微刻时标",
    storyLine: "最后一小时，光有了心跳。",
  },
  {
    serial: "N-0509",
    title: "Tide Return Aquamarine Cuff",
    seriesId: "tide-return",
    category: "bracelet",
    zhTitle: "归潮海蓝宝手环",
    image: "/assets/products/n-0509-tide-return-aquamarine-cuff.png",
    materialLine: "铂金 / 海蓝宝 / 贝母 / 天然白钻",
    craftLine: "水纹雕刻 / 半透明珐琅 / 隐秘式镶嵌 / 镜面抛光",
    storyLine: "回来不是重复旧路，是以另一种蓝色抵达自己。",
  },
  {
    serial: "N-0510",
    title: "Tender Armor Obsidian Ring",
    seriesId: "tender-armor",
    category: "ring",
    zhTitle: "温柔盔甲黑曜守戒",
    image: "/assets/products/n-0510-tender-armor-obsidian-ring.png",
    materialLine: "铂金 / 黑玛瑙 / 祖母绿 / 天然白钻",
    craftLine: "钢琴烤漆 / 隐秘式镶嵌 / 微密镶 / 镜面抛光",
    storyLine: "黑色不是防备，是把柔软留给值得靠近的人。",
  },
  {
    serial: "N-0511",
    title: "Moon Archive Lapis Studs",
    seriesId: "moon-archive",
    category: "stud",
    zhTitle: "月相档案青金石耳钉",
    image: "/assets/products/n-0511-moon-archive-lapis-studs.png",
    materialLine: "青金石 / 铂金 / 蓝宝石 / 天然白钻",
    craftLine: "贝母薄片镶嵌 / 微密镶 / 玑镂雕纹 / 微刻封存线",
    storyLine: "月光不替你遗忘，只把深蓝色的证据留到你愿意翻阅那天。",
  },
  {
    serial: "N-0512",
    title: "Ash Garden Phoenix Earrings",
    seriesId: "ash-garden",
    category: "earring",
    zhTitle: "灰烬花园赤羽耳环",
    image: "/assets/products/n-0512-ash-garden-phoenix-earrings.png",
    materialLine: "玫瑰金 / 红宝石 / 尖晶石 / 暖色珐琅",
    craftLine: "鎏金鎏彩 / 微密镶 / 冷珐琅 / 手工錾刻",
    storyLine: "废墟里的第一束火，不需要被允许也会重新升起。",
  },
  {
    serial: "N-0519",
    title: "Ash Garden Meteorite Witness Brooch",
    seriesId: "ash-garden",
    category: "brooch",
    zhTitle: "灰烬花园陨铁证词胸针",
    image: "/assets/products/n-0519-ash-garden-meteorite-brooch.png",
    materialLine: "钛金属 / 陨铁 / 烟晶 / 暗红珐琅 / 天然白钻 / 黑陶瓷",
    craftLine: "陶瓷烧结 / 局部氧化 / 雪花镶 / 微密镶",
    storyLine: "一块陨铁是灰烬后的证据，它不说话，但它从不撤销。",
  },
];

export const internalProductConceptSeeds: DailyProductSeed[] = [
  {
    serial: "N-0516",
    title: "Justice of One Palimpsest Verdict Brooch",
    seriesId: "justice-of-one",
    category: "brooch",
    zhTitle: "唯一的证明·覆写判决胸针",
    image: "/assets/product-concepts/n-0516-justice-palimpsest-brooch.png",
    materialLine: "黑铑铂金 / 钯金 / 陨石 / 天然白钻 / 帕拉伊巴碧玺",
    craftLine: "错金银 / 手工錾刻 / 玑镂雕纹 / 雪花镶 / 隐秘式镶嵌",
    storyLine:
      "被涂黑的判决不是结案，而是证据改变了出现的方式：黑铑的低声把愤怒收进结构里；陨石的纹路像无法伪造的时间戳，把被抹去的名字重新压印出来。雪花镶让白钻像冷静的目击者，而错金银与錾刻把“真相曾被覆盖”这一事实，变成无法再被覆盖的纹理。",
  },
  {
    serial: "N-0517",
    title: "Still Here Anodized Titanium Rift Ring",
    seriesId: "still-here",
    category: "ring",
    zhTitle: "仍在这里·钛蓝裂光开口戒",
    image: "/assets/product-concepts/n-0517-still-here-titanium-rift-ring.png",
    materialLine: "钛金属 / 碳纤维 / 黑陶瓷 / 红色尖晶石 / 天然白钻",
    craftLine: "钛金属阳极氧化 / 陶瓷烧结 / 隐秘式镶嵌 / 拉丝雾面 / 微密镶",
    storyLine:
      "Still Here 从不把裂痕刻掉，但会把它放在能呼吸、能发光的位置：钛金属阳极氧化出的蓝像“重新能说话”的气息；碳纤维和黑陶瓷把脆弱变成支撑；红尖晶石被隐秘式镶嵌在缺口边缘，像一句低声但坚定的“我还在”。",
  },
  {
    serial: "N-0518",
    title: "Seventh Light Lacquered Cloisonne Watch",
    seriesId: "seventh-light",
    category: "watch",
    zhTitle: "第七日·墨彩珐琅漆面腕表",
    image: "/assets/product-concepts/n-0518-seventh-light-lacquer-cloisonne-watch.png",
    materialLine: "黑陶瓷 / 黑贝母 / 天然白钻 / 帕拉伊巴碧玺 / 坦桑石",
    craftLine: "钢琴烤漆 / 透光珐琅 / 景泰蓝灵感配色 / 玑镂雕纹 / 隐秘式镶嵌",
    storyLine:
      "第七日最后一小时，归属像一只不可撤回的秒针：黑陶瓷让时间更沉稳，黑贝母把“说不出口”的部分藏进内光；透光珐琅与漆面层层叠加，把等待做成可被看见的深度；帕拉伊巴与坦桑石像两束不同方向的光，提醒你——不是所有迟到都是错过，有些迟到是清算后的回归。",
  },
];

const seedAuctionEndsAt = [
  "2026-07-24T20:00:00+08:00",
  "2026-07-16T20:00:00+08:00",
  "2026-06-06T20:00:00+08:00",
  "2026-05-27T20:00:00+08:00",
  "2026-05-27T20:30:00+08:00",
  "2026-05-28T20:00:00+08:00",
  "2026-05-28T20:30:00+08:00",
  "2026-05-29T20:00:00+08:00",
  "2026-05-29T20:30:00+08:00",
  "2026-05-30T20:00:00+08:00",
  "2026-05-30T20:30:00+08:00",
  "2026-06-01T20:00:00+08:00",
  "2026-06-01T20:30:00+08:00",
  "2026-06-02T20:00:00+08:00",
  "2026-06-02T20:30:00+08:00",
  "2026-06-03T20:00:00+08:00",
  "2026-06-03T20:30:00+08:00",
  "2026-06-04T20:00:00+08:00",
  "2026-06-04T20:30:00+08:00",
  "2026-06-05T20:00:00+08:00",
];

const dailyProductArchiveOverrides: Record<string, Pick<Product, "status" | "ownerNickname" | "soldAt">> = {
  "N-0529": {
    status: "sold",
    ownerNickname: "Archive Review",
    soldAt: "2026-06-01T20:00:00+08:00",
  },
};

function splitSeedLine(line: string) {
  return line
    .split("/")
    .map((item) => item.trim())
    .filter(Boolean);
}

function seedSizing(category: Product["category"]) {
  if (category === "ring") return "开放式戒臂，可按佩戴者手寸微调，内侧保留舒适弧面。";
  if (category === "bracelet") return "开放式手环结构，可按腕围微调，交付前确认佩戴弧度。";
  if (category === "watch") return "腕表链节或表带支持多档调节，交付前按腕围确认孔位。";
  if (category === "necklace") return "链长可调节，支持锁骨链与常规项链两档佩戴。";
  if (category === "brooch") return "胸针安全锁结构，可佩戴于西装、丝巾或礼服。";
  return "标准耳针结构，可按需要提供耳夹改造咨询。";
}

function createProductFromSeed(seed: DailyProductSeed, index: number): Product {
  const materials = splitSeedLine(seed.materialLine);
  const archiveOverride = dailyProductArchiveOverrides[seed.serial];
  const craft = splitSeedLine(seed.craftLine);
  const startPrice = suggestStartPrice({
    category: seed.category,
    materials,
    craft,
    seriesId: seed.seriesId,
  });

  return {
    id: seed.serial.toLowerCase(),
    slug: `${seed.seriesId}-${seed.serial.toLowerCase()}`,
    serial: seed.serial,
    title: seed.title,
    zhTitle: seed.zhTitle,
    seriesId: seed.seriesId,
    category: seed.category,
    inspiration: seed.storyLine,
    concept: `${seed.storyLine} 这一件以顶级奢侈品级材质、工艺和故事线共同构成唯一记忆，只制作一个实体，不复制、不复刻；完成 USDT 到账确认后只归属一位主人。`,
    materials,
    craft,
    startPrice,
    currentPrice: startPrice,
    depositAmount: 0,
    bidIncrement: 0,
    bids: 0,
    endsAt: seedAuctionEndsAt[index] ?? seedAuctionEndsAt[0],
    status: archiveOverride?.status ?? "live",
    ownerNickname: archiveOverride?.ownerNickname,
    soldAt: archiveOverride?.soldAt,
    image: seed.image,
    sizing: seedSizing(seed.category),
    engraving: `内侧或背面微刻 ${seed.serial}，作为 Noirven 唯一编号印记。`,
    pricingBasis: luxuryPricingBasis(),
  };
}

const curatedProducts: Product[] = [
  {
    id: "n-0101",
    slug: "still-here-ring-n-0101",
    serial: "N-0101",
    title: "Still Here Riftlight Ring",
    zhTitle: "仍在这里裂光戒",
    seriesId: "still-here",
    category: "ring",
    inspiration: "我还在，所以光也还在。",
    concept:
      "铂金与玫瑰金形成不完全闭合的活口戒臂，黑色钢琴烤漆裂隙旁嵌入一颗天然白钻。它把裂缝变成结构，把低谷之后仍然站立的姿态固定下来。",
    materials: ["铂金", "玫瑰金", "天然白钻"],
    craft: ["钢琴烤漆", "珐琅彩"],
    startPrice: 77800,
    currentPrice: 108200,
    depositAmount: 6200,
    bidIncrement: 1900,
    bids: 16,
    endsAt: "2026-05-26T21:00:00+08:00",
    status: "live",
    image: "/assets/products/n-0101-still-here-ring.png",
    sizing: "活口戒臂，可按佩戴者手寸微调；内侧保留舒适弧面。",
    engraving: "戒臂内侧刻印 N-0101。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0102",
    slug: "still-here-bracelet-n-0102",
    serial: "N-0102",
    title: "Still Here Quiet Rift Bracelet",
    zhTitle: "仍在这里静裂手环",
    seriesId: "still-here",
    category: "bracelet",
    inspiration: "不是修补伤口，而是承认伤口之后仍然完整。",
    concept:
      "开放式手环用玫瑰金与铂金保留一处清晰负空间，珐琅裂隙与微钻光点形成 Still Here 系列的识别。",
    materials: ["玫瑰金", "铂金", "天然白钻"],
    craft: ["珐琅彩", "钢琴烤漆"],
    startPrice: 103800,
    currentPrice: 103800,
    depositAmount: 8300,
    bidIncrement: 3100,
    bids: 0,
    endsAt: "2026-05-27T19:30:00+08:00",
    status: "waiting",
    image: "/assets/products/n-0102-still-here-bracelet.png",
    sizing: "开放式活口手环，适配多数腕围，可由交付前微调弧度。",
    engraving: "手环内侧刻印 N-0102。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0103",
    slug: "still-here-brooch-n-0103",
    serial: "N-0103",
    title: "Still Here Witness Brooch",
    zhTitle: "仍在这里证光胸针",
    seriesId: "still-here",
    category: "brooch",
    inspiration: "伤口之后，仍有形态。",
    concept:
      "铂金线条被一处黑色烤漆裂隙打断，玫瑰金底面托住微小白钻，像一份安静但不可撤销的证明。",
    materials: ["铂金", "玫瑰金", "天然白钻"],
    craft: ["钢琴烤漆", "雕金"],
    startPrice: 103800,
    currentPrice: 137900,
    depositAmount: 8300,
    bidIncrement: 3100,
    bids: 11,
    endsAt: "2026-05-25T22:20:00+08:00",
    status: "sold",
    ownerNickname: "Still Here",
    soldAt: "2026-05-18T22:20:00+08:00",
    image: "/assets/products/n-0103-still-here-brooch.png",
    sizing: "胸针背扣为安全锁结构，不涉及尺码；可佩戴于西装、丝巾或礼服。",
    engraving: "胸针背面刻印 N-0103。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0201",
    slug: "unclaimed-star-pendant-n-0201",
    serial: "N-0201",
    title: "Awaiting Star Lapis Necklace",
    zhTitle: "待归之星星芒项链",
    seriesId: "unclaimed-star",
    category: "necklace",
    inspiration: "不是无人喜欢，只是尚未遇见唯一的主人。",
    concept:
      "青金石与贝母组成非具象悬浮切面，一颗天然白钻被极细铂金线托住。它不画星星，却让等待唯一归属的时刻自己发光。",
    materials: ["铂金", "青金石", "贝母", "天然白钻"],
    craft: ["珐琅彩", "鎏彩"],
    startPrice: 89800,
    currentPrice: 89800,
    depositAmount: 7200,
    bidIncrement: 2200,
    bids: 0,
    endsAt: "2026-05-28T20:00:00+08:00",
    status: "waiting",
    image: "/assets/products/n-0201-unclaimed-star-pendant.png",
    sizing: "链长可调节，支持锁骨链与常规项链两档佩戴。",
    engraving: "吊坠背面刻印 N-0201。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0202",
    slug: "unclaimed-star-studs-n-0202",
    serial: "N-0202",
    title: "Awaiting Star Whisper Studs",
    zhTitle: "待归之星星语耳钉",
    seriesId: "unclaimed-star",
    category: "stud",
    inspiration: "等待不是空白，是归属发生之前的序章。",
    concept:
      "一对不完全对称耳钉以青金石、贝母和白钻形成悬浮星点，但避开直白星形，让识别来自留白和比例。",
    materials: ["铂金", "青金石", "贝母", "天然白钻"],
    craft: ["珐琅彩"],
    startPrice: 65800,
    currentPrice: 77000,
    depositAmount: 5300,
    bidIncrement: 1600,
    bids: 7,
    endsAt: "2026-05-24T18:10:00+08:00",
    status: "sold",
    ownerNickname: "Starless",
    soldAt: "2026-05-17T18:10:00+08:00",
    image: "/assets/products/n-0202-unclaimed-star-studs.png",
    sizing: "耳钉为标准针式结构，不涉及尺码。",
    engraving: "耳钉背托刻印 N-0202。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0203",
    slug: "unclaimed-star-earring-n-0203",
    serial: "N-0203",
    title: "Awaiting Star Drift Earring",
    zhTitle: "待归之星星渡耳环",
    seriesId: "unclaimed-star",
    category: "earring",
    inspiration: "被看见之前，它已经独一无二。",
    concept:
      "细长铂金结构悬挂青金石与贝母切面，一颗白钻像被延迟认出的光，整体保持轻盈而不对称。",
    materials: ["铂金", "青金石", "贝母", "天然白钻"],
    craft: ["珐琅彩", "鎏彩"],
    startPrice: 85800,
    currentPrice: 102600,
    depositAmount: 6900,
    bidIncrement: 2100,
    bids: 8,
    endsAt: "2026-05-26T17:45:00+08:00",
    status: "live",
    image: "/assets/products/n-0203-unclaimed-star-earring.png",
    sizing: "耳环为标准耳针结构，可提供耳夹改造咨询。",
    engraving: "耳环背部微刻 N-0203。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0301",
    slug: "seventh-light-ring-n-0301",
    serial: "N-0301",
    title: "Seventh Light Last Hour Ring",
    zhTitle: "第七日归光戒",
    seriesId: "seventh-light",
    category: "ring",
    inspiration: "第七日，光有了归属。",
    concept:
      "黄金与玫瑰金在活口戒臂上形成七段细线，一颗偏移彩宝打破完美对称，像最后一小时出现的答案。",
    materials: ["黄金", "玫瑰金", "彩色宝石", "天然白钻"],
    craft: ["鎏金", "鎏彩"],
    startPrice: 88800,
    currentPrice: 130600,
    depositAmount: 7100,
    bidIncrement: 2200,
    bids: 19,
    endsAt: "2026-05-23T21:00:00+08:00",
    status: "live",
    image: "/assets/products/n-0301-seventh-light-ring.png",
    sizing: "活口戒臂，可覆盖常见手寸区间并支持交付前微调。",
    engraving: "戒臂内侧刻印 N-0301。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0302",
    slug: "seventh-light-earrings-n-0302",
    serial: "N-0302",
    title: "Seventh Light Turning Earrings",
    zhTitle: "第七日回时耳环",
    seriesId: "seventh-light",
    category: "earring",
    inspiration: "最后一小时的归属反转。",
    concept:
      "一对耳环以七段金线和偏移彩色宝石组成时间韵律，左右轻微不对称，仍然保持同一秩序。",
    materials: ["玫瑰金", "黄金", "彩色宝石", "天然白钻"],
    craft: ["鎏金", "鎏彩"],
    startPrice: 92800,
    currentPrice: 92800,
    depositAmount: 7400,
    bidIncrement: 2300,
    bids: 0,
    endsAt: "2026-05-29T19:20:00+08:00",
    status: "waiting",
    image: "/assets/products/n-0302-seventh-light-earrings.png",
    sizing: "标准耳针结构，可提供耳夹改造咨询。",
    engraving: "耳环背面刻印 N-0302。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0303",
    slug: "seventh-light-watch-n-0303",
    serial: "N-0303",
    title: "Seventh Light Belonging Watch",
    zhTitle: "第七日归属腕表",
    seriesId: "seventh-light",
    category: "watch",
    inspiration: "时间让光有了归处。",
    concept:
      "轻薄珠宝腕表以贝母盘面和七枚极细时标表达归属时刻，表冠旁的偏移彩宝让时间不再只是计量，而是归属发生的瞬间。",
    materials: ["玫瑰金", "铂金", "贝母", "彩色宝石"],
    craft: ["鎏金", "鎏彩", "钢琴烤漆"],
    startPrice: 158800,
    currentPrice: 158800,
    depositAmount: 12700,
    bidIncrement: 4800,
    bids: 0,
    endsAt: "2026-05-30T22:00:00+08:00",
    status: "waiting",
    image: "/assets/products/n-0303-seventh-light-watch.png",
    sizing: "腕表表带支持多档调节，交付前按腕围确认孔位或链节。",
    engraving: "表背刻印 N-0303。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0401",
    slug: "justice-of-one-brooch-n-0401",
    serial: "N-0401",
    title: "Justice of One Evidence Brooch",
    zhTitle: "唯一的证明证光胸针",
    seriesId: "justice-of-one",
    category: "brooch",
    inspiration: "不由多数定义，只由唯一确认。",
    concept:
      "雕金平衡线被一颗偏心孔雀石打破，再由景泰蓝色面重新建立秩序。它像一份无声证词，证明独特不需要多数同意。",
    materials: ["雕金", "孔雀石", "彩色宝石", "天然白钻"],
    craft: ["景泰蓝", "鎏金", "雕金"],
    startPrice: 134800,
    currentPrice: 182800,
    depositAmount: 10800,
    bidIncrement: 4000,
    bids: 12,
    endsAt: "2026-05-25T22:10:00+08:00",
    status: "live",
    image: "/assets/products/n-0401-justice-of-one-brooch.png",
    sizing: "胸针安全锁结构，不涉及尺码，可佩戴于多种面料。",
    engraving: "胸针背面刻印 N-0401。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0402",
    slug: "justice-of-one-cuff-n-0402",
    serial: "N-0402",
    title: "Justice of One Balance Bracelet",
    zhTitle: "唯一的证明衡线手环",
    seriesId: "justice-of-one",
    category: "bracelet",
    inspiration: "为被低估的独特，保留一次公平展示。",
    concept:
      "开放式雕金手环用孔雀石偏心打破平衡，景泰蓝线条重新建立秩序，让活口本身成为 Justice of One 的判断线。",
    materials: ["雕金", "黄金", "孔雀石", "天然白钻"],
    craft: ["景泰蓝", "鎏金", "雕金"],
    startPrice: 122800,
    currentPrice: 122800,
    depositAmount: 9800,
    bidIncrement: 3700,
    bids: 0,
    endsAt: "2026-05-29T20:40:00+08:00",
    status: "waiting",
    image: "/assets/products/n-0402-justice-of-one-cuff.png",
    sizing: "开放式活口手环，可按腕围微调，开口处为设计核心。",
    engraving: "手环内侧刻印 N-0402。",
    pricingBasis: luxuryPricingBasis(),
  },
  {
    id: "n-0403",
    slug: "justice-of-one-ring-n-0403",
    serial: "N-0403",
    title: "Justice of One Verdict Ring",
    zhTitle: "唯一的证明裁光戒",
    seriesId: "justice-of-one",
    category: "ring",
    inspiration: "被证明之前，它已经成立。",
    concept:
      "雕金与铂金交错形成偏心活口戒，一枚深绿色宝石与景泰蓝细线构成证据般的光点。",
    materials: ["雕金", "铂金", "孔雀石", "天然白钻"],
    craft: ["景泰蓝", "雕金"],
    startPrice: 93800,
    currentPrice: 114500,
    depositAmount: 7500,
    bidIncrement: 2300,
    bids: 9,
    endsAt: "2026-05-24T23:10:00+08:00",
    status: "live",
    image: "/assets/products/n-0403-justice-of-one-ring.png",
    sizing: "活口戒臂，可按佩戴者手寸微调；偏心结构是设计特征。",
    engraving: "戒臂内侧刻印 N-0403。",
    pricingBasis: luxuryPricingBasis(),
  },
];

function repriceLuxuryProduct(product: Product): Product {
  const startPrice = suggestStartPrice({
    category: product.category,
    materials: product.materials,
    craft: product.craft,
    seriesId: product.seriesId,
  });

  return {
    ...product,
    startPrice,
    currentPrice: startPrice,
    depositAmount: 0,
    bidIncrement: 0,
    bids: 0,
    status: product.status === "sold" ? "sold" : "live",
    pricingBasis: luxuryPricingBasis(),
  };
}

export const products: Product[] = [...dailyProductSeeds.map(createProductFromSeed), ...curatedProducts.map(repriceLuxuryProduct)];

export const liveProducts = products.filter((product) => product.status !== "sold");
export const soldProducts = products.filter((product) => product.status === "sold");

export const adminMetrics: AdminMetric[] = [
  { label: "Live Belonging", value: "27", detail: "New story-backed product images are listed first" },
  { label: "Story Series", value: "08", detail: "Ready for IP, short drama, game extension" },
  { label: "Pending Settlement", value: "$220k+", detail: "USDT transfer proofs waiting for admin confirmation" },
  { label: "Generated Drafts", value: "17", detail: "Seed prompts stay internal; only finished product images are public" },
];

export function getSeries(seriesId: string) {
  return storySeries.find((series) => series.id === seriesId);
}

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
